# Generated by Django 2.2.8 on 2020-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('shopName', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'shopDetails',
            },
        ),
    ]
