# Generated by Django 2.2.8 on 2020-05-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200506_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetails',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
